services:
  meltryllis:
    image: nowaru124/meltryllis:latest
    stop_signal: SIGKILL
    container_name: meltryllis-bot
    restart: on-failure:2
    environment:
      DISCORD_BOT_TOKEN:
      HOST_DISCORD_USER_ID:
      REPORT_CHANNEL_ID:
      DEBUG_MODE: #para activar usa "on", "true" o "1".
      # lenguaje
      LANGS_SUPPORTED: es # para añadir mas necesitar crear las traducciones
      LOCALE: es
      # Timmers
      YT_RSSCHECK_TIME: #esto ya cuenta con tiempo minimo interno
      REDDIT_RSSCHECK_TIME: # esto cuanta con tiempoo minimo interno
      REDDIT_CLIENT_ID: #checalo en tu APP panel  
      REDDIT_CLIENT_SECRET: #checalo en tu APP panel  
      EMBEDEZ_REDDITCHECK: # off si quieres que no use embedez y solo los dominios de reddit
      MANGADEX_CHECK_TIMME: #esto ya cuenta con tiempo minimo interno
      # Configs
      WELCOME_BANNER_URL:
      PUID:
      PGID:
      TZ: #zona horaria, necesaria para /cronpost
      # DB configs 
      DB_HOST:
      DB_USER:
      DB_PASSWORD:
      DB_DATABASE:
      # Lavalink configs  
      LAVALINK_NAME:
      LAVALINK_HOST:
      LAVALINK_PORT:
      LAVALINK_PASSWORD:
    depends_on: mariadb
    # Descomenta "lavalink" si vas a hostear tu propio server lavalink 
    #     lavalink  
    volumes: meltryllis_data/logs:/app/logs

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: meltryllis-bd
    ports: 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      PGID:
      PUID:
    volumes: meltryllis_data/db:/var/lib/mysql

############## Si buscas hostear tu propio server lavalink descomenta esto ##############
#  lavalink:
#    image: ghcr.io/lavalink-devs/lavalink:4-alpine
#    restart: unless-stopped
#    container_name: meltryllis-lavalink
#    ports:
#      2333:2333
#    environment:
#      LAVALINK_SERVER_PASSWORD:
#    volumes:
#      meltryllis_data/lavalink/data:/data
#      ./application.yml:/opt/Lavalink/application.yml

volumes:
  meltryllis_data:
